name: BloomWorld CI

on:
  pull_request:
    branches:
      - main

jobs:
  shop-service-ci:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: shop-service

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: shop-service/package-lock.json


      - name: Install dependencies
        run: npm ci


      - name: Check Node.js application syntax
        run: node --check server.js


      - name: Run tests
        run: npm test
        continue-on-error: true


      - name: Build Docker image
        run: docker build -t shop-service:ci .
